# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='group_name',
            field=models.CharField(help_text='Assign a Group Name to the Student.', max_length=100, unique=True, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='students_contact_csv',
            field=models.FileField(help_text="You can download the sample csv file <a href='/media/sample_contacts.csv'>here</a>", null=True, upload_to='', verbose_name='Contacts File'),
        ),
    ]
