# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0002_auto_20171101_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterAssignment',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField(verbose_name='Due Date for the Assignment')),
                ('assignment_attachement', models.FileField(upload_to='', verbose_name='Assignment Related Files')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(verbose_name='Description of the Assignment')),
                ('special_instructions', models.TextField(verbose_name='Guidelines for the Assignment')),
                ('student_group', models.ManyToManyField(to='Classroom.StudentGroup')),
            ],
        ),
    ]
