# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0003_masterassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterassignment',
            name='subject',
            field=models.CharField(default='General', max_length=255),
        ),
    ]
