# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0004_masterassignment_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterHandout',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handout_attachment', models.FileField(upload_to='', verbose_name='Assignment Related Files')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(verbose_name='Description of the Assignment')),
                ('subject', models.CharField(default='General', max_length=255)),
                ('student_group', models.ManyToManyField(to='Classroom.StudentGroup')),
            ],
        ),
    ]
