# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Classroom', '0003_masterassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_text', models.TextField(blank=True, help_text='Write your Assignment Submission', null=True, verbose_name='Assignment Submission')),
                ('due_date', models.DateField(verbose_name='Due Date for the Assignment')),
                ('assignment_attachement', models.FileField(upload_to='', verbose_name='Assignment Related Files')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(verbose_name='Description of the Assignment')),
                ('special_instructions', models.TextField(verbose_name='Guidelines for the Assignment')),
                ('submission_attachment', models.FileField(help_text='For multiple file upload please make a zip file.', upload_to='', verbose_name='Submission Attachment')),
                ('master_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.MasterAssignment')),
                ('student', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Classroom.Student')),
            ],
        ),
    ]
