# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClassroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='subject',
            field=models.CharField(default='General', max_length=255),
        ),
    ]
