# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0005_masterhandout'),
        ('MyClassroom', '0002_assignmentsubmission_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handout',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(default='General', max_length=255)),
                ('handout_attachment', models.FileField(upload_to='', verbose_name='Handout Related Files')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(verbose_name='Description of the Assignment')),
                ('master_handout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.MasterHandout')),
                ('student', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Classroom.Student')),
            ],
        ),
    ]
